import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Cherry_Bomb_One, Quicksand } from "next/font/google";

import "./globals.css";
//const inter = Inter({ subsets: ["latin"] });

const inter = Quicksand({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Playbook quiz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className = "bg-slate-800">
          {children}
          </div></body>
      </Providers>
    </html>
  );
}
